# Generated by Django 4.2.5 on 2023-11-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
