# Generated by Django 4.2.5 on 2023-11-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_alter_notes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
